version: 2
registries:
  rubygems-server-rubygems-pkg-github-com:
    type: rubygems-server
    url: https://rubygems.pkg.github.com
    token: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - jalyna
  ignore:
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
  - dependency-name: actionpack
    versions:
    - 6.1.2.1
  - dependency-name: rails
    versions:
    - 6.1.2
  - dependency-name: rubocop
    versions:
    - 1.9.0
  registries:
  - rubygems-server-rubygems-pkg-github-com
